//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_batches
    {
        public int id { get; set; }
        public string f_nom { get; set; }
        public string f_type { get; set; }
        public string f_execution { get; set; }
        public string f_sendmail { get; set; }
        public string f_destinataires { get; set; }
        public string f_description { get; set; }
        public string f_infofrequence { get; set; }
        public string f_fileexecuted { get; set; }
    }
}
