//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_clubs
    {
        public int id { get; set; }
        public string f_club { get; set; }
        public string f_clubname { get; set; }
        public string f_responsable { get; set; }
        public string f_province { get; set; }
        public string f_adresse { get; set; }
        public string f_cp { get; set; }
        public string f_pays { get; set; }
        public string f_ville { get; set; }
        public string f_phone { get; set; }
        public string f_email { get; set; }
        public string f_siteweb { get; set; }
        public Nullable<int> f_actif { get; set; }
        public string f_entry_dt { get; set; }
        public string f_siteweb_visible { get; set; }
        public string f_map_lat { get; set; }
        public string f_map_lng { get; set; }
        public string f_map_remarques { get; set; }
        public string f_map_icon { get; set; }
        public string f_map_options { get; set; }
        public string f_file { get; set; }
        public string f_photo { get; set; }
    }
}
