//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.MSSQL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_competitions_officiels
    {
        public int id { get; set; }
        public int f_competition_id { get; set; }
        public int f_officiel_id { get; set; }
        public string f_role_id { get; set; }
        public int f_order { get; set; }
        public int f_status_id { get; set; }
        public string f_comment { get; set; }
        public string f_creation_dt { get; set; }
        public string f_update_dt { get; set; }
    }
}
