//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.MSSQL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_convocations
    {
        public int id { get; set; }
        public string f_convocation { get; set; }
        public string f_club { get; set; }
        public string f_dateheure_1 { get; set; }
        public string f_dateheure_2 { get; set; }
        public string f_nom { get; set; }
        public string f_nature { get; set; }
        public string f_lieu_1 { get; set; }
        public string f_lieu_2 { get; set; }
        public string f_lieu_3 { get; set; }
        public string f_divers { get; set; }
        public string f_no { get; set; }
        public string f_secretaire_1 { get; set; }
        public string f_secretaire_2 { get; set; }
        public string f_secretaire_3 { get; set; }
        public string f_directeur_1 { get; set; }
        public string f_directeur_2 { get; set; }
        public string f_creation_dt { get; set; }
        public string f_update_dt { get; set; }
    }
}
