//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_convocations_epreuves
    {
        public int id { get; set; }
        public int f_convocation_id { get; set; }
        public string f_sexe { get; set; }
        public string f_category { get; set; }
        public int f_epreuve_id { get; set; }
        public string f_epreuve_type { get; set; }
        public string f_epreuve_nom { get; set; }
    }
}
