//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_compteurvisites
    {
        public int id { get; set; }
        public string f_page { get; set; }
        public Nullable<int> f_nbrvisites { get; set; }
        public string f_lastvisite_dt { get; set; }
    }
}
