//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.MSSQL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_download
    {
        public int id { get; set; }
        public string f_action { get; set; }
        public string f_document { get; set; }
        public string f_groupe { get; set; }
        public string f_region { get; set; }
        public Nullable<int> f_actif { get; set; }
        public string f_file { get; set; }
        public Nullable<int> f_count { get; set; }
        public string f_new { get; set; }
        public string f_entry_dt { get; set; }
        public Nullable<int> f_file_groupe { get; set; }
    }
}
