//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.MSSQL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_formations
    {
        public int id { get; set; }
        public System.DateTime f_date { get; set; }
        public string f_heure { get; set; }
        public string f_lieu { get; set; }
        public string f_plan { get; set; }
    }
}
