//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_mailinglist
    {
        public int id { get; set; }
        public string f_nom { get; set; }
        public string f_prenom { get; set; }
        public string f_email { get; set; }
        public Nullable<int> f_actif { get; set; }
        public string f_typeimport { get; set; }
        public string f_entry_dt { get; set; }
    }
}
