//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_md_status_compet
    {
        public int id { get; set; }
        public string f_status { get; set; }
        public int f_order { get; set; }
        public int f_delta { get; set; }
        public byte f_coefficient { get; set; }
    }
}
