//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_md_saisons
    {
        public int id { get; set; }
        public string f_saison { get; set; }
        public System.DateTime f_start_dt { get; set; }
        public System.DateTime f_end_dt { get; set; }
    }
}
