//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.MSSQL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_messages_recipients
    {
        public int id { get; set; }
        public Nullable<int> f_id_messages { get; set; }
        public string f_to_mail { get; set; }
        public string f_to_name { get; set; }
        public string f_from_mail { get; set; }
        public string f_from_name { get; set; }
        public string f_mail_type { get; set; }
        public string f_confirmreadingto { get; set; }
        public Nullable<int> f_actif { get; set; }
        public string f_langue { get; set; }
        public string f_entry_dt { get; set; }
        public string f_out_dt { get; set; }
        public string f_errorinfo { get; set; }
        public Nullable<int> f_retry { get; set; }
    }
}
