//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_menu_left
    {
        public int id { get; set; }
        public string f_menu_name { get; set; }
        public string f_menu_file { get; set; }
        public string f_situation { get; set; }
        public Nullable<int> f_menu_actif { get; set; }
        public string f_entry_dt { get; set; }
        public string f_menu_new { get; set; }
        public Nullable<int> f_ordre { get; set; }
    }
}
