//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.MSSQL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_membres_acces
    {
        public int id { get; set; }
        public string f_nom { get; set; }
        public string f_prenom { get; set; }
        public string f_nbrmembre { get; set; }
        public string f_login { get; set; }
        public string f_password { get; set; }
        public string f_phone { get; set; }
        public string f_phone2 { get; set; }
        public string f_brevet { get; set; }
        public string f_role { get; set; }
        public string f_acces { get; set; }
        public string f_entryDT { get; set; }
        public string f_email_1 { get; set; }
        public string f_email_2 { get; set; }
        public string f_email_3 { get; set; }
        public string f_anniversaire_dt { get; set; }
        public string f_entry_dt { get; set; }
        public Nullable<int> f_actif { get; set; }
        public string f_sexe { get; set; }
        public string f_phone_visible { get; set; }
        public string f_email_visible { get; set; }
        public string f_adresse { get; set; }
        public string f_cp { get; set; }
        public string f_ville { get; set; }
        public string f_pays { get; set; }
        public string f_dan_dt { get; set; }
        public string f_photo { get; set; }
        public string f_infosupp { get; set; }
        public Nullable<int> f_nbrmembre_famille { get; set; }
        public string f_lastupdate_who { get; set; }
        public string f_lastupdate_dt { get; set; }
    }
}
