//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_news
    {
        public int id { get; set; }
        public string f_entry_dt { get; set; }
        public string f_comment { get; set; }
        public int f_actif { get; set; }
        public string f_subject { get; set; }
        public string f_photo_1 { get; set; }
        public string f_photo_2 { get; set; }
    }
}
