//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.MSSQL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_officiels_meritants
    {
        public int id { get; set; }
        public int f_annee { get; set; }
        public string f_nom { get; set; }
        public Nullable<int> f_officiel_id { get; set; }
        public string f_remarque { get; set; }
    }
}
