//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_quiz_answers
    {
        public int id { get; set; }
        public int id_question { get; set; }
        public string f_answers_fr { get; set; }
        public string f_answers_nl { get; set; }
        public string f_answers_en { get; set; }
        public int f_result { get; set; }
    }
}
