//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_quiz_questions
    {
        public int id { get; set; }
        public string f_brevet_level { get; set; }
        public string f_subject { get; set; }
        public string f_question_fr { get; set; }
        public string f_question_image_fr { get; set; }
        public string f_question_nl { get; set; }
        public string f_question_image_nl { get; set; }
        public string f_question_en { get; set; }
        public string f_question_image_en { get; set; }
        public Nullable<int> f_actif { get; set; }
        public string f_entry_dt { get; set; }
    }
}
