//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_quiz_history
    {
        public int id { get; set; }
        public string f_filename { get; set; }
        public string f_brevet_level { get; set; }
        public string f_langue { get; set; }
        public Nullable<int> f_nbr_questions { get; set; }
        public string f_list_ids { get; set; }
        public Nullable<int> f_actif { get; set; }
        public string f_entry_dt { get; set; }
        public string f_nbrinstructor { get; set; }
    }
}
