//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_roles
    {
        public string id { get; set; }
        public string f_nom { get; set; }
        public int f_ordre { get; set; }
        public int f_xls_ligne { get; set; }
        public string f_xls_col { get; set; }
        public int f_brevet_id { get; set; }
    }
}
