//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.MSSQL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_sites
    {
        public int id { get; set; }
        public string f_site_name { get; set; }
        public string f_site_url { get; set; }
        public Nullable<int> f_site_actif { get; set; }
        public string f_entry_dt { get; set; }
        public string f_site_category { get; set; }
        public string f_site_category_ordre { get; set; }
    }
}
