//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.MSSQL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_sondage_answers
    {
        public int id { get; set; }
        public int id_sondage_questions { get; set; }
        public string f_reponse_fr { get; set; }
        public string f_reponse_nl { get; set; }
        public string f_reponse_en { get; set; }
        public int f_nb_reponses { get; set; }
    }
}
