//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_test_xls
    {
        public int id { get; set; }
        public string f_fichier { get; set; }
        public string f_ligne { get; set; }
        public string f_colonne { get; set; }
        public string f_valeur { get; set; }
    }
}
