//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.MSSQL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Jubilaires
    {
        public string nom { get; set; }
        public string prenom { get; set; }
        public string club { get; set; }
        public Nullable<int> nb_années { get; set; }
    }
}
