//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ListeDesOfficielsDeBruxelles
    {
        public string Nom { get; set; }
        public string Prénom { get; set; }
        public string Surnom { get; set; }
        public string Club { get; set; }
        public string Province { get; set; }
        public int Brevet { get; set; }
        public string Tél { get; set; }
        public string Tél2 { get; set; }
        public string Email { get; set; }
        public string Courrier_papier { get; set; }
        public string Adresse { get; set; }
        public string CP { get; set; }
        public string Ville { get; set; }
    }
}
