//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DAL.MSSQL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_OfficielBruxellesFull
    {
        public string nickname { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<int> isPostalMail { get; set; }
        public string f_club { get; set; }
        public Nullable<System.DateTime> b1 { get; set; }
        public Nullable<System.DateTime> b2 { get; set; }
        public Nullable<System.DateTime> b3 { get; set; }
        public Nullable<System.DateTime> ITOA { get; set; }
        public Nullable<System.DateTime> ITOW { get; set; }
        public Nullable<int> m1 { get; set; }
        public Nullable<int> m2 { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string sex { get; set; }
        public string birthday { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string postalCode { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string phone { get; set; }
        public string phone2 { get; set; }
    }
}
