//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DataLayer.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class AthleteJuryEntities : DbContext
    {
        public AthleteJuryEntities()
            : base("name=AthleteJuryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<t_competitions> t_competitions { get; set; }
        public DbSet<t_md_saisons> t_md_saisons { get; set; }
        public DbSet<t_membres> t_membres { get; set; }
        public DbSet<t_membres_acces> t_membres_acces { get; set; }
        public DbSet<t_officiels> t_officiels { get; set; }
    
        public virtual ObjectResult<usp_OfficielsMeritantsList_Result> usp_OfficielsMeritantsList(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_OfficielsMeritantsList_Result>("usp_OfficielsMeritantsList", yearParameter);
        }
    
        public virtual ObjectResult<usp_Upcomingcompetitions_Result> usp_Upcomingcompetitions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Upcomingcompetitions_Result>("usp_Upcomingcompetitions");
        }
    }
}
