//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuryAthlete.DataLayer.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_membres
    {
        public int id { get; set; }
        public string f_nom { get; set; }
        public string f_prenom { get; set; }
        public string f_phone { get; set; }
        public Nullable<int> f_brevet { get; set; }
        public string f_email { get; set; }
        public string f_email2 { get; set; }
        public string f_email3 { get; set; }
        public Nullable<System.DateTime> f_anniversaire { get; set; }
        public Nullable<System.DateTime> f_entry_dt { get; set; }
        public Nullable<int> f_actif { get; set; }
        public string f_sexe { get; set; }
        public string f_phone_visible { get; set; }
        public string f_email_visible { get; set; }
        public string f_adresse { get; set; }
        public string f_cp { get; set; }
        public string f_ville { get; set; }
        public Nullable<System.DateTime> f_dan_dt { get; set; }
        public string f_photo { get; set; }
        public string f_membre { get; set; }
    }
}
